# Generated by Django 5.0.7 on 2025-03-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitlog',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
